apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: canary
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: canary
    - apiVersion: v1
      kind: Service
      name: canary
  placement:
    clusterAffinity:
      clusterNames:
        - member1
        - member2
    replicaScheduling:
      replicaSchedulingType: Divided
      replicaDivisionPreference: Weighted
      weightPreference:
        staticWeightList:
          - targetCluster:
              clusterNames:
                - member1
            weight: 1
          - targetCluster:
              clusterNames:
                - member2
            weight: 1
